export { default as Header } from "./Header/Header";
export { default as Navbar } from "./Navbar/Navbar";
export { default as ProfileContainer } from "./Profile/ProfileContainer";
export { default as DialogsContainer } from "./Dialogs/DialogsContainer";
export { default as News } from "./News/News";
export { default as Music } from "./Music/Music";
export { default as Settings } from "./Settings/Settings";
export { default as UsersContainer } from "./Users/UsersContainer";
export { default as HeaderContainer } from "./Header/HeaderContainer";
